### ISSUE TITLE
StackOverflowError error spam

### ISSUE THREAD

**Issue by runescapejon** [FTBTeam/FTB-Quests#387] opened 2020-03-15 20:45 UTC
I get this error spam https://pastebin.com/raw/pD5BB06t
Sorry i don't know how to reproduce it happen about twice already.
Also, that i am indeed on version `1.8.0.237`

EDIT: it seem this crash report is starting to happen more often.

**Comment by runescapejon** [comment] 2020-03-15 22:03
Also, that it seem to always happen once this player join the server
https://pastebin.com/raw/Dmi75TZs

**Comment by runescapejon** [comment] 2020-03-16 01:33
update info..

It's possible that since this mod was added to my server and that they were players online before this mod got added. Also, that those players had inventory few items in their inventory. That the quest book was attempting to put it to their inventory but couldn't.. We had found this out by removing the player inventory and they can successfully join the server without crashing the server. I don't know if this is helpful just trying to provide as much information as possible.

**Comment by ProperSAMA** [comment] 2020-03-17 16:52
I have a similar problem.
crash-report: https://pastebin.com/B8pJFuT8
Hope to be useful for developers.

**Comment by ProperSAMA** [comment] 2020-03-17 18:50
After a few hours of work, I may understand the cause of the problem.
If there is something in the player's inventory before installing ftbquest. And these items can accomplish a task. Then there will be problems.
Don't make the task that requires items the first task. There seems to be no problem.
I enabled "autocreate_mp". Maybe it's also related to this.

**Comment by MaxNeedsSnacks** [comment] 2021-02-12 18:40
This should be fixed in newer versions of FTB Quests for 1.16, and maybe in newer 1.12 updates as well

**Closed** 2021-02-12 18:39 UTC
