### ISSUE TITLE
propose

### ISSUE THREAD

**Issue by axin0452** [FTBTeam/FTB-Quests#362] opened 2019-11-14 03:59 UTC
Can you add a cool down time for repetitive tasks？

**Comment by pyure** [comment] 2020-02-09 17:43
Seconded.  But please, dude, use an actual descriptive title.  It was hard to find this before I duplicated the same request.

**Comment by pyure** [comment] 2020-02-09 17:45
Duplicate of #303

**Comment by pyure** [comment] 2020-02-09 17:46
Duplicate of #72

**Comment by MaxNeedsSnacks** [comment] 2021-02-12 17:23
Duplicate of #72

**Closed by MaxNeedsSnacks** 2021-02-12 17:23 UTC
