### ISSUE TITLE
quest progress not syning between team members

### ISSUE THREAD

**Issue by Spongman** [FTBTeam/FTB-Quests#486] opened 2020-11-16 05:15 UTC
I'm running ftb-quests-1502.0.2.252.jar (in 'Craft to Exile [Dissonance]') on a server, i have 2 playesr that are in a team together, but FTB quest progress isn't shared between the players.

**Comment by Spongman** [comment] 2020-11-16 05:50
this works in 1.12 (ME^5), but not in 1.15 apparently ?

**Comment by Spongman** [comment] 2020-11-16 07:38
I tried adding the 1.15 ftp-teams mod to both server & clients, and used `/ftbteams` to add both players to an ftb team, but that didn't help. still not synced.

**Comment by MokahTGS** [comment] 2020-11-19 16:39
This has been reported for 1.16+ as well.  Seems to be a 1.15 and forward issue.

**Comment by MaxNeedsSnacks** [comment] 2021-02-12 17:42
Duplicate of #470

**Closed by MaxNeedsSnacks** 2021-02-12 17:42 UTC
