### ISSUE TITLE
Suggestion: Option to have the completion of one quest remove (hide) another quest

### ISSUE THREAD

**Issue by clubpetey** [FTBTeam/FTB-Quests#327] opened 2019-07-27 03:17 UTC
You can currently make a quest dependent on another quest, but I would like to add the reverse.  A quest where if any (or all) of the dependent quests are completed the current quest is deleted or hidden.   This feature would naturally require that quests can be hidden and only exposed when the pre-reqs are completed.

The purpose here would be to make quests lines that have "your choices matter"  A quest you choose to complete would affect what you can do later in the story.  I could also see extending this to look at the specific reward you selected and have different quests show/hide based on that selection.  But as a first step, having one quest hide another would allow for some re-playability to mod packs.

**Comment by bshelden** [comment] 2019-08-08 04:49
Another use case for this is providing a choice of starting kit.

**Comment by Wip-Sama** [comment] 2021-02-08 18:45
Still no news?

**Comment by MaxNeedsSnacks** [comment] 2021-02-12 17:24
Duplicate of #265

**Closed by MaxNeedsSnacks** 2021-02-12 17:24 UTC
