### ISSUE TITLE
[Suggestion] Cooldown on repeatable quests and ability to completely hide quests.

### ISSUE THREAD

**Issue by OrionAF** [FTBTeam/FTB-Quests#303] opened 2019-06-13 01:11 UTC
Give us an option to make a quest repeatable but on a cooldown.  Good for servers who want to have daily/weekly/monthly quests.  

Also to be able to completely hide quests, so they can only be seen in edit mode.

**Comment by pyure** [comment] 2020-02-09 17:46
Duplicate of #72

**Comment by MaxNeedsSnacks** [comment] 2021-02-12 17:24
As already stated by pyure: This is a duplicate of #72

**Closed by MaxNeedsSnacks** 2021-02-12 17:24 UTC
Labels: Suggestion / ToDo
