### ISSUE TITLE
[bug] NoClassDefFound after failing to change quest icon

### ISSUE THREAD

**Issue by NillerMedDild** [FTBTeam/FTB-Quests#618] opened 2021-08-16 19:51 UTC
To help us help you, please provide as much information as you can, this helps us with debugging and reproducting the issue.

**Mod & Pack version**
ftb-quests-forge-1605.3.3-build.49

**Forge / Fabric version, if applicable**
Forge

**Modpack (with version), if applicable**
Enigmatica 6 0.5.10-in-dev

**If the issue is a crash; An external link to the crash report**
https://gist.github.com/NillerMedDild/d8aea6e148bbfe0a0687fda4331e5401

**How to reproduce the issue**
- Open quests
- Create a quest
- Try to edit it's icon, 
- Click all the buttons in the icon selection screen (I believe the 2nd button crashed for me)

**A screenshot, if applicable**

**Anything else we should know?**

**Comment by NillerMedDild** [comment] 2021-08-16 20:11
Actually, just making a quest triggers it.

**Comment by MaxNeedsSnacks** [comment] 2021-08-16 20:15
> SelectItemStackScreen
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by MaxNeedsSnacks** [comment] 2021-08-16 20:16
Duplicate of https://github.com/FTBTeam/FTB-Quests/issues/602, now if you'd excuse me, I'll go cry into a pillow for a bit

**Closed by MaxNeedsSnacks** 2021-08-16 20:16 UTC
