### ISSUE TITLE
[Feature Request] Anti-dependents

### ISSUE THREAD

**Issue by RobinNightWing** [FTBTeam/FTB-Quests#441] opened 2020-07-22 20:37 UTC
Please allow us to make quests that lock other quests. We have quests that cannot be completed if they dont have a certain quest unlocked, can you please add a feature where a quest cannot be completed if they do have a certain quest. Something like this would also be useful for locking the shop, if they have a certain quest completed, they can no longer purchase an item from shop. The possibilities :o
See the professionally drawn image to see what im talking about
![image](https://user-images.githubusercontent.com/27363790/88226124-9dbf8d00-cc39-11ea-8e62-96fb91dc6d8b.png)

**Comment by MaxNeedsSnacks** [comment] 2021-02-12 19:01
Duplicate of #265

**Closed by MaxNeedsSnacks** 2021-02-12 19:01 UTC
