### ISSUE TITLE
Client side doesn't load quests on server

### ISSUE THREAD

**Issue by Naturaspell** [FTBTeam/FTB-Quests#557] opened 2021-03-07 11:14 UTC
It seems that client side doesn't load quests when you are on a server. Causing crash if you use the quests book or the keybind.
You have to load quests on a client world before connecting to a server to get it work.

Forge: 36.0.46
FTB Quests : 1605.2.0-build.32

**Comment by aikidojohn** [comment] 2021-03-07 16:44
I ran into this as well. I believe this is because the client is sending a server side event to Kube JS here : https://github.com/FTBTeam/FTB-Quests/blob/master/common/src/main/java/com/feed_the_beast/ftbquests/integration/kubejs/KubeJSIntegration.java#L50

Kube JS throws a NPE instead of returning false in this case. I produced a build of ftbquests that functions correctly (as far as I can tell) by wrapping all of the server events in that file in a try catch and swallowing the exception. Obviously that's not a good solution, I just wanted to prove that this was the actual problem.

**Comment by Naturaspell** [comment] 2021-03-07 17:18
Thanks for help. I didn't see the exception with kubejs in logs. I believe client try to use the server script manager, that doesn't exist. But I don't really know how kubejs works so maybe I'm wrong.

**Comment by MaxNeedsSnacks** [comment] 2021-03-07 18:16
Do both of you have an example of your crash logs by any chance?

**Comment by Naturaspell** [comment] 2021-03-07 18:51
Of course.

The exception in logs is long so I send it as a text file. The game doesn't crash at this point.
[KubeJS_exception.log](https://github.com/FTBTeam/FTB-Quests/files/6097748/KubeJS_exception.log)

Crash when using the quests book
![image](https://user-images.githubusercontent.com/80199784/110250868-fa2fac80-7f7d-11eb-88d5-f688f2653412.png)

Crash when using the keybind.
![image](https://user-images.githubusercontent.com/80199784/110250912-3e22b180-7f7e-11eb-875f-68efe1492126.png)

The error message in inventory when using the book icon.
![image](https://user-images.githubusercontent.com/80199784/110250947-6f9b7d00-7f7e-11eb-9007-c523429ea8d1.png)

**Comment by aikidojohn** [comment] 2021-03-07 21:27
[ftbquests_exception.txt](https://github.com/FTBTeam/FTB-Quests/files/6097985/ftbquests_exception.txt)

Yep, here you go. This happens on the client when I connect to the server. The server log has nothing out of the ordinary.

**Comment by MaxNeedsSnacks** [comment] 2021-03-08 00:15
@aikidojohn Your bug is in conjunction with Just Enough Resources, which doesn't expect a `null` loot table to be returned.

@Naturaspell Are you sure FTB Quests is installed on the server, and that it's on the latest version?

**Comment by MaxNeedsSnacks** [comment] 2021-03-08 00:23
> I ran into this as well. I believe this is because the client is sending a server side event to Kube JS here : https://github.com/FTBTeam/FTB-Quests/blob/master/common/src/main/java/com/feed_the_beast/ftbquests/integration/kubejs/KubeJSIntegration.java#L50

The problem isn't any sort of "sidedness" issue from what I can tell, it's more that the server script manager isn't ready yet when this event is fired for the first time. I'll see what's causing this

**Comment by MaxNeedsSnacks** [comment] 2021-03-17 23:06
This should be fixed in newer releases; can you still reproduce this?

**Comment by Naturaspell** [comment] 2021-03-18 08:07
It seems to be fixed. Thank you.

**Closed** 2021-03-19 10:49 UTC
Labels: bug
