### ISSUE TITLE
Task names don't show up. Also other letters too.

### ISSUE THREAD

**Issue by mamiopro** [FTBTeam/FTB-Quests#467] opened 2020-10-16 10:59 UTC
I don't know if it is the modpack (Craft to Exile Dissonance) but i don't think so. MC version: 1.16.1
![Ekran görüntüsü 2020-10-16 135737](https://user-images.githubusercontent.com/36071689/96250544-a7962980-0fb7-11eb-9426-51be762f3548.png)
![Ekran görüntüsü 2020-10-16 135805](https://user-images.githubusercontent.com/36071689/96250546-a8c75680-0fb7-11eb-9851-9cd175d3839f.png)

I use Twitch launcher. Nothing unusual done. Didn't modified the pack.

**Comment by MaxNeedsSnacks** [comment] 2021-02-12 18:25
Duplicate of #505 
(...ish, either way it should be fixed on newer versions of FTB Quests for 1.16.4+, so if Craft Of Exile hasn't updated yet, please ask the pack dev to do so)

**Closed by MaxNeedsSnacks** 2021-02-12 18:25 UTC
