### ISSUE TITLE
[1.16.4] Shared Progress using FTBTeams

### ISSUE THREAD

**Issue by MokahTGS** [FTBTeam/FTB-Quests#470] opened 2020-10-19 17:20 UTC
We have a private server with three people on the same team and quests when completed by one person are not completing for everyone on the team.

There also is not GUI button for team management.

Everyone has to complete the quests individually.  There doesn't seem to be any way of changing this.

Version FTBQuests-1202.9.0.13

**Comment by Spongman** [comment] 2020-11-16 04:30
is this supposed to work?

**Comment by MokahTGS** [comment] 2020-11-16 15:36
Yup...supposed to complete quests for everyone on the same team.  Does not however.

**Comment by HoNGamer** [comment] 2020-12-16 18:24
Got the same problem in TNP:Limitless 3

**Comment by MokahTGS** [comment] 2020-12-29 16:23
Can this get the bug tag added to it so it actually gets fixed??

It's been reported multiple times.

**Comment by sanchits2003** [comment] 2021-01-14 01:49
It's funny how the FtbQuests description is a "team-based questing mod" yet the main team aspect of it is bugged out.

**Comment by Gbergz** [comment] 2021-02-03 12:45
Needs to be fixed asap! It's still an issue.

**Comment by Spongman** [comment] 2021-02-04 08:56
try asking on the discord? i did a while ago while the mod author was on, but he completely ignored my comment.

**Comment by MokahTGS** [comment] 2021-02-04 18:14
I've tried Discord as well...also ignored completely.

**Comment by MokahTGS** [comment] 2021-02-05 17:44
So got an answer on Discord:

https://www.dropbox.com/s/v0cntqjt58tbpxy/bug470.jpg?dl=0

It's a feature that is not currently added back into to the 1.16.4 version but will be added back at some point.  So it is known and planned to fix, but no eta.

**Comment by MaxNeedsSnacks** [comment] 2021-02-12 17:43
As @MokahTGS already said, this is not a bug but instead a missing feature that will be added back at some later point.

**Comment by orblazer** [comment] 2021-03-22 08:56
Hello,
We have some idea of possible date for that feature ?

**Comment by MokahTGS** [comment] 2021-05-30 18:18
Has this been fixed?  I heard a rumor it was but this is still open.

**Comment by Quezler** [comment] 2021-05-31 12:00
@MokahTGS kinda seems that way yes: https://github.com/FTBTeam/FTB-Quests/commits/main (probably still _some_ bugs)

**Comment by Gbergz** [comment] 2021-05-31 12:16
Definitely has bugs still. Not pack ready imho.

**Comment by yuty89** [comment] 2021-06-22 05:19
Is this still at all useable?  Friend and I's quests arent syncing and I think I have everything set up correctly.

**Comment by MaxNeedsSnacks** [comment] 2021-06-22 08:05
@yuty89 If you and your friend are in the same party, try regjoining the server and see whether it works then, because quest sync **should** be up and running now

**Comment by drag498** [comment] 2021-06-22 23:36
Playing 1.16.5 pack with latest version of ftb quest, 1605.2.1-build 39, and having issues with quests not syncing

**Comment by MokahTGS** [comment] 2021-06-23 01:42
Yeah quests not syncing on either TNP Limitless or Enigmatica 6

**Comment by Quezler** [comment] 2021-06-23 07:31
> Yeah quests not syncing with updated FTB Quests on either TNP Limitless or Enigmatica 6

did you try it with just an updated ftb quests, or also simultaneously with ftb teams? (assuming they synergize)

**Comment by MokahTGS** [comment] 2021-06-23 14:17
Honestly can't say I have since my whole point of using this mod is to be used in modpacks.

**Comment by yuty89** [comment] 2021-06-23 14:45
updated to most current seaopolis which had an update to ftbquests, its working now, at least for me

**Comment by Quezler** [comment] 2021-06-23 14:47
@yuty89 could you list the versions of quests & teams used in that pack? (or the entire modlist with versions if you have it)

**Comment by yuty89** [comment] 2021-06-23 16:40
ftbquests: 1605.3.2-build.24    ftbteams: 1605.2.1-build.12
list for all mods https://www.curseforge.com/minecraft/modpacks/seaopolis/files/3359597

**Comment by MaxNeedsSnacks** [comment] 2021-06-25 23:53
All the issues with progress should be fixed in the newest release ^^
Please make a separate issue for any other things you may encounter regarding to progress!

**Closed by MaxNeedsSnacks** 2021-06-25 23:53 UTC
Labels: feature

**Comment by Gbergz** [comment] 2021-06-26 00:20
> All the issues with progress should be fixed in the newest release ^^
> Please make a separate issue for any other things you may encounter regarding to progress!

Sweet! Though latest release requires FTB Library version 1605.3.1-build.35, latest available on CurseForge is build.33
![image](https://user-images.githubusercontent.com/26634554/123495708-120e6780-d625-11eb-9a36-6407b9e10f8e.png)

**Comment by MaxNeedsSnacks** [comment] 2021-06-26 00:49
Oh yeah, that's because 35 was a dev release, we're gonna publish 36 in a second so you guys can get going

**Comment by Spongman** [comment] 2021-10-04 01:26
Thank you, thank you! This is working great in FTB OceanBlock!
