### ISSUE TITLE
[1.16.5 Forge]The special inventory to select items for quest don't show up, can someone help?

### ISSUE THREAD

**Issue by Sacri-Pan** [FTBTeam/FTB-Quests#602] opened 2021-06-13 17:52 UTC
![2021-06-13_16 45 46](https://user-images.githubusercontent.com/74361905/121817295-ccdf5280-cc80-11eb-83b4-074918554a18.png)

**Comment by BovineShaman** [comment] 2021-06-28 16:07
I also have this problem, haven't found a solution yet

**Comment by MaxNeedsSnacks** [comment] 2021-06-28 16:18
What versions of FTB Library are you two running? Updating those along with Architectury **should** usually solve this issue

**Comment by BovineShaman** [comment] 2021-06-28 16:26
1605.2.1.41, for FTB Library, 1605.2.1-build.39 for quests

It's part of the ATM6 pack, and they do plan on updating it, but I'm trying to make quests to go along with that update because apparently updating all the ftb mods may reset quest progression. We want to have more quests for people to complete, to lessen the blow of losing quest progress.

**Comment by MaxNeedsSnacks** [comment] 2021-06-28 16:33
Oh it *may* not just reset progression, it currently ***definitely*** does, but yeah, this *should* be fixed in the newer versions

**Comment by BovineShaman** [comment] 2021-06-28 16:38
I just reduced my ram from 16GB to 8GB and it now works, weird

**Comment by muqsit-0010** [comment] 2021-07-10 23:08
Any solution to this? It is a real nuisance, seems to appear randomly. It is really hard to pin point what exactly is causing it but seems to be related to memory allocation.

- There is always a MissingClassDefinitionError related to this in log
- In this specific case the missing class (at runtime) is ItemStackButton
- There are a lot of other errors and crashes because of MissingClassDefinitionError, some already reported in the issues.
- It is always in Items Search Thread
- So it is related to ThreadItemList
- The more the mods in a modpack the worse the issue gets
- Doing any kind of aggressive GC with G1GC or CMS makes the issue permanent in large modpacks
- Removing aggressive GC seems to fix the problem occasionally

**Comment by muqsit-0010** [comment] 2021-07-15 03:54
Ok, I finally figured it out. The classes from FTB Library are getting GC'd for one reason or another in larger modpacks.
**Referencing to an FTB Library class before ThreadItemList is engaged fixes the issue.** 

**My speculative theory** is that the class loader of the aforementioned ThreadItemList thread cannot directly load the classes and only copies the classpath from TrasformClassLoader when the thread is created. At that point the copied over classpath is already missing FTB Library classes and hence MissingClassDefinitionError. 
In my intuition, the reason for FTB Library classes getting GC'd is that they are never referenced anywhere before ThreadItemList is engaged.

**Hacky Solution**
For now I am keeping a custom mod in my local modpack with only one line in the constructor of the main class, which fixes the issue:

` ExampleMod.LOGGER.info(Class.forName(SelectItemStackScreen.class.getCanonicalName()+"$ItemStackButton"));`


As the ItemStackButton is referenced so it never gets GC'd along with preventing the GC of other FTB classes.

**Comment by LatvianModder** [comment] 2021-07-15 07:45
Thank you for looking into this, it helps a lot! I've never had such weird issue before

**Comment by MaxNeedsSnacks** [comment] 2021-07-15 08:32
So, as it turns out, the Conc Mark Sweep GC unloads unused classes by default now (see https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8000325), which means that @muqsit-0010's theory is probably spot on (as G1 is also set to unload classes)

For testing purposes, would it be possible for anyone in this thread to reproduce this with the `-XX:+TraceClassUnloading` launch option enabled? I'll try to do it myself, as well, but obviously, I don't have the same modpacks and system specs as you guys at the ready, unfortunately, so this may take me a while

**Comment by muqsit-0010** [comment] 2021-07-17 03:02
So, -XX:+TraceClassUnloading doesn't log any class unloading events, which means that FTB Library classes aren't getting loaded in the first place? It is also double confirmed by the fact that using -noclassgc VM argument does not fix the MissingClassDefinitionError.


That begs the question then, why are the classes loading in smaller modpacks? According to the Java Specification [Section 12.2.1](https://docs.oracle.com/javase/specs/jls/se6/html/execution.html#12.2.1) A class loader can "prefetch them based on expected usage". That could be the reason.



[gclog.txt](https://github.com/FTBTeam/FTB-Quests/files/6834064/gclog.txt)
[latest.log](https://github.com/FTBTeam/FTB-Quests/files/6833921/latest.log)

**Comment by MaxNeedsSnacks** [comment] 2021-07-17 10:58
> So, -XX:+TraceClassUnloading doesn't log any class unloading events, which means that FTB Library classes aren't getting loaded in the first place? 

Not necessarily, Forge has a special classloading marker that needs to be set for it to log these things (`-Dforge.logging.debugFile.level=TRACE -Dforge.logging.marker.classloading=ACCEPT`). Unfortunately, it seems that setting this marker crashes my game on startup with SOF errors.

**Comment by muqsit-0010** [comment] 2021-07-18 06:27
Using only -Dforge.logging.debugFile.level=TRACE and **omitting** -Dforge.logging.marker.classloading=ACCEPT prevents the SOF errors and is logging the loading information at least.
Still not able to get Unloading logs unfortunately.

**Comment by muqsit-0010** [comment] 2021-07-18 07:36
Also, adding the following to ThreadItemList constructor fixes the issue.

`this.setContextClassLoader(SelectItemStackScreen.class.getClassLoader());`

**Comment by muqsit-0010** [comment] 2021-08-07 10:27
Ok, that did not fix the issue in the latest version. I realize that it was not the line itself but the act of me referencing SelectItemStackScreen from a mixin, in another private quick fix mod, which fixed the issue. 🤦
Should have tested the line directly compiled in ftb-library source before suggesting, sorry, my bad. 

The worst thing is the time it takes to load a large modpack after each change. Makes testing agonizing. 

Only solution which definitely has worked until now is referencing any one of the previously non-referenced classes, before ThreadItemList.run() is executed. Referencing them beforehand prevents them from ever unloading.

e.g. from a static initializer within SeletItemStackScreen
```
static {
    //Creating an instance would also work as it is a reference.
    FTBLibrary.LOGGER.info(ItemStackButton.getCanonicalName());
}
```
or a reference to a class within the constructor of FTBLibrary class. (This time I actually thoroughly tested these.)

But it seems like a hacky solution...

**Comment by MaxNeedsSnacks** [comment] 2021-08-13 17:02
It was worth a shot haha

> But it seems like a hacky solution...

Indeed it does, so we might just either rewrite it or make it synchronous, since this bit isn't user-facing and we can at least cache the "ALL ITEMS" list, the initial performance penalty seems *fine* to me

**Comment by MaxNeedsSnacks** [comment] 2021-08-19 14:01
Found a fix that doesn't require me to compromise on async searches, currently testing it on the [dev](https://github.com/FTBTeam/FTB-Library/tree/dev) branch of GUI Lib ^^

If you want to help test it, grab the latest version of FTB Library from [here](https://vers.saps.dev/) (scroll down to Forge or Fabric depending on what loader you use and click the download button on the left), but keep in mind that you may **not** publish modpack updates with these versions until we've actually released them!

**Comment by muqsit-0010** [comment] 2021-08-20 00:50
It is actually working! 
![image](https://cdn.betterttv.net/emote/5b1740221c5a6065a7bad4b5/1x)

**Closed** 2021-08-20 01:04 UTC
Labels: bug, priority: high, needs testing
