### ISSUE TITLE
Add Reverse Dependency

### ISSUE THREAD

**Issue by MinerBryan** [FTBTeam/FTB-Quests#302] opened 2019-06-12 12:24 UTC
Basically lock quests after a quest has been completed. Not much to explain. Perhaps an example would be nice?

'The Bones Quest' can buy 1 bone for 20 FTB Money coins. If the Mob_grinding_utils mod quest is completed, 'The Bones Quest' is locked and another quest opens, this new quests buys 1 bone for 10 FTB Money coins.

**Comment by RobinNightWing** [comment] 2020-07-22 20:54
this would be very cool.

**Comment by MaxNeedsSnacks** [comment] 2021-02-12 17:23
Duplicate of #265

**Closed by MaxNeedsSnacks** 2021-02-12 17:23 UTC
Labels: Suggestion / ToDo
