### ISSUE TITLE
Crash when entering the 'select item' screen

### ISSUE THREAD

**Issue by pm065** [FTBTeam/FTB-Quests#592] opened 2021-05-30 11:43 UTC
FTB Quests: 1605.3.2-build.10
FTB Lib: 1605.3.1-build.12
Crash report: https://paste.ee/p/s2SHT
Rolling back one version on Quests, Teams and Lib fixes the issue.

**Comment by ReeCodes** [comment] 2021-06-07 10:18
Same

**Comment by MaxNeedsSnacks** [comment] 2021-08-18 14:13
Duplicate of #602, I'm assuming

**Closed by MaxNeedsSnacks** 2021-08-18 14:13 UTC
